package com.jc.dao;

import com.jc.entity.Agency;
import com.jc.entity.AgencyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AgencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_agency
     *
     * @mbggenerated
     */
    int countByExample(AgencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_agency
     *
     * @mbggenerated
     */
    int deleteByExample(AgencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_agency
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_agency
     *
     * @mbggenerated
     */
    int insert(Agency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_agency
     *
     * @mbggenerated
     */
    int insertSelective(Agency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_agency
     *
     * @mbggenerated
     */
    List<Agency> selectByExample(AgencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_agency
     *
     * @mbggenerated
     */
    Agency selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_agency
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Agency record, @Param("example") AgencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_agency
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Agency record, @Param("example") AgencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_agency
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Agency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_agency
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Agency record);
}