package com.jc.dao;

import com.jc.entity.Refund;
import com.jc.entity.RefundExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RefundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_refund
     *
     * @mbggenerated
     */
    int countByExample(RefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_refund
     *
     * @mbggenerated
     */
    int deleteByExample(RefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_refund
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_refund
     *
     * @mbggenerated
     */
    int insert(Refund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_refund
     *
     * @mbggenerated
     */
    int insertSelective(Refund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_refund
     *
     * @mbggenerated
     */
    List<Refund> selectByExample(RefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_refund
     *
     * @mbggenerated
     */
    Refund selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_refund
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Refund record, @Param("example") RefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_refund
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Refund record, @Param("example") RefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_refund
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Refund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_refund
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Refund record);
}