package com.jc.entity;

public class Bank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_bank.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_bank.merchantid
     *
     * @mbggenerated
     */
    private Integer merchantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_bank.bankname
     *
     * @mbggenerated
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_bank.bankuser
     *
     * @mbggenerated
     */
    private String bankuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_bank.bankno
     *
     * @mbggenerated
     */
    private String bankno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_bank.id
     *
     * @return the value of cs_bank.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_bank.id
     *
     * @param id the value for cs_bank.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_bank.merchantid
     *
     * @return the value of cs_bank.merchantid
     *
     * @mbggenerated
     */
    public Integer getMerchantid() {
        return merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_bank.merchantid
     *
     * @param merchantid the value for cs_bank.merchantid
     *
     * @mbggenerated
     */
    public void setMerchantid(Integer merchantid) {
        this.merchantid = merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_bank.bankname
     *
     * @return the value of cs_bank.bankname
     *
     * @mbggenerated
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_bank.bankname
     *
     * @param bankname the value for cs_bank.bankname
     *
     * @mbggenerated
     */
    public void setBankname(String bankname) {
        this.bankname = bankname == null ? null : bankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_bank.bankuser
     *
     * @return the value of cs_bank.bankuser
     *
     * @mbggenerated
     */
    public String getBankuser() {
        return bankuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_bank.bankuser
     *
     * @param bankuser the value for cs_bank.bankuser
     *
     * @mbggenerated
     */
    public void setBankuser(String bankuser) {
        this.bankuser = bankuser == null ? null : bankuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_bank.bankno
     *
     * @return the value of cs_bank.bankno
     *
     * @mbggenerated
     */
    public String getBankno() {
        return bankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_bank.bankno
     *
     * @param bankno the value for cs_bank.bankno
     *
     * @mbggenerated
     */
    public void setBankno(String bankno) {
        this.bankno = bankno == null ? null : bankno.trim();
    }
}