package com.jc.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jc.entity.Consume;
import com.jc.entity.ConsumeExample;

public interface ConFailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_confail
     *
     * @mbggenerated
     */
    int countByExample(ConsumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_confail
     *
     * @mbggenerated
     */
    int deleteByExample(ConsumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_confail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer csid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_confail
     *
     * @mbggenerated
     */
    int insert(Consume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_confail
     *
     * @mbggenerated
     */
    int insertSelective(Consume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_confail
     *
     * @mbggenerated
     */
    List<Consume> selectByExample(ConsumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_confail
     *
     * @mbggenerated
     */
    Consume selectByPrimaryKey(Integer csid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_confail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Consume record, @Param("example") ConsumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_confail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Consume record, @Param("example") ConsumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_confail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Consume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_confail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Consume record);
}