package com.jc.dao;

import com.jc.entity.Bank;
import com.jc.entity.BankExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_bank
     *
     * @mbggenerated
     */
    int countByExample(BankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_bank
     *
     * @mbggenerated
     */
    int deleteByExample(BankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_bank
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_bank
     *
     * @mbggenerated
     */
    int insert(Bank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_bank
     *
     * @mbggenerated
     */
    int insertSelective(Bank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_bank
     *
     * @mbggenerated
     */
    List<Bank> selectByExample(BankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_bank
     *
     * @mbggenerated
     */
    Bank selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_bank
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Bank record, @Param("example") BankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_bank
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Bank record, @Param("example") BankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_bank
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Bank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_bank
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Bank record);
}